In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Preparing Data<br>
Includes bias term<br>
AND GATE 

In [0]:
X=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y=np.array([[0],[0],[0],[1]])
print(X,Y)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]] [[0]
 [0]
 [0]
 [1]]


In [0]:
print(X.shape,Y.shape)

(4, 3) (4, 1)


In [0]:
#theta=np.array([[10],[20],[30]])
theta=np.random.rand(3,1)
alpha=0.003
print(theta,theta.shape)
m,n=X.shape
print(m,n)

[[0.4834304 ]
 [0.31231343]
 [0.67808619]] (3, 1)
4 3


In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
for i in range(10000):
  h=sigmoid(X.dot(theta))
  d=(Y.dot(np.log(h).T)) + (1-Y).dot(np.log(1-h).T)
  cost=-(1/m)*(d)
  theta=theta- alpha*(X.T.dot(h-Y))
  if i%100==0:
    print(theta)



[[0.4777818 ]
 [0.31080532]
 [0.67636045]]
[[-0.00561104]
 [ 0.20266883]
 [ 0.54450323]]
[[-0.3518721 ]
 [ 0.16640798]
 [ 0.48380846]]
[[-0.60445084]
 [ 0.17772366]
 [ 0.47239484]]
[[-0.79758243]
 [ 0.21718107]
 [ 0.49126672]]
[[-0.95307032]
 [ 0.27252068]
 [ 0.527972  ]]
[[-1.08419286]
 [ 0.3364071 ]
 [ 0.5748895 ]]
[[-1.19907983]
 [ 0.40445894]
 [ 0.62739207]]
[[-1.30279326]
 [ 0.47404568]
 [ 0.68265849]]
[[-1.39854083]
 [ 0.54359126]
 [ 0.73896636]]
[[-1.48838893]
 [ 0.61216559]
 [ 0.79527099]]
[[-1.57369079]
 [ 0.67923874]
 [ 0.85094986]]
[[-1.6553486 ]
 [ 0.74452959]
 [ 0.90564469]]
[[-1.73397652]
 [ 0.80791125]
 [ 0.95916239]]
[[-1.81000316]
 [ 0.86935138]
 [ 1.01141258]]
[[-1.88373647]
 [ 0.9288744 ]
 [ 1.06236796]]
[[-1.95540511]
 [ 0.98653764]
 [ 1.11203918]]
[[-2.02518492]
 [ 1.04241628]
 [ 1.16045896]]
[[-2.09321595]
 [ 1.09659397]
 [ 1.20767209]]
[[-2.15961348]
 [ 1.14915705]
 [ 1.25372924]]
[[-2.22447525]
 [ 1.20019107]
 [ 1.29868307]]
[[-2.28788616]
 [ 1.24977874]
 [ 1.34

In [0]:
def predict(t,x):
  return sigmoid(x.dot(t))

In [0]:
print(theta)
ans=predict(theta,np.array([[1,0,1]]))
ans=ans[0][0]
print(round(ans))


[[-5.24103215]
 [ 3.35381623]
 [ 3.35646317]]
0.0


Data for OR Gate

In [0]:
X1=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y1=np.array([[0],[1],[1],[1]])


In [0]:
theta1=np.random.rand(3,1)
alpha=0.003

m,n=X1.shape
print(m,n)

4 3


In [0]:
for i in range(10000):
  h=sigmoid(X1.dot(theta1))
  d=(Y1.dot(np.log(h).T)) + (1-Y1).dot(np.log(1-h).T)
  cost=-(1/m)*(d)
  theta1=theta1- alpha*(X1.T.dot(h-Y1))
  if i%100==0:
    print(theta1)

[[0.43483623]
 [0.74830014]
 [0.7069055 ]]
[[0.42653868]
 [0.85204948]
 [0.8127925 ]]
[[0.40512687]
 [0.94607029]
 [0.90874993]]
[[0.37506503]
 [1.03289057]
 [0.99734442]]
[[0.33930875]
 [1.11417015]
 [1.08026337]]
[[0.29987454]
 [1.19104307]
 [1.15866097]]
[[0.25816774]
 [1.26430986]
 [1.23335287]]
[[0.21518164]
 [1.33455136]
 [1.30493152]]
[[0.1716239 ]
 [1.40219913]
 [1.37383766]]
[[0.12799986]
 [1.46758071]
 [1.44040621]]
[[0.08466927]
 [1.53094954]
 [1.5048967 ]]
[[0.04188583]
 [1.59250533]
 [1.567514  ]]
[[-1.74634460e-04]
 [ 1.65240821e+00]
 [ 1.62842265e+00]]
[[-0.04139375]
 [ 1.71078877]
 [ 1.68775709]]
[[-0.08169565]
 [ 1.7677552 ]
 [ 1.74562892]]
[[-0.12103589]
 [ 1.82339856]
 [ 1.80213227]]
[[-0.15939319]
 [ 1.87779659]
 [ 1.85734766]]
[[-0.19676321]
 [ 1.93101666]
 [ 1.91134499]]
[[-0.23315389]
 [ 1.98311783]
 [ 1.96418566]]
[[-0.26858197]
 [ 2.03415254]
 [ 2.01592426]]
[[-0.30307029]
 [ 2.08416784]
 [ 2.06660986]]
[[-0.33664582]
 [ 2.13320635]
 [ 2.11628695]]
[[-0.3693381

In [0]:
print(theta1)
ans=predict(theta1,np.array([[1,1,1]]))
ans=ans[0][0]
print(round(ans))

[[-1.69325345]
 [ 4.43196703]
 [ 4.42962649]]
1.0


Data for NOT GATE

In [0]:
X2=np.array([[1,0],[1,1]])
Y2=np.array([[1],[0]])
print(X2,Y2)

[[1 0]
 [1 1]] [[1]
 [0]]


In [0]:
theta2=np.random.rand(2,1)
alpha=0.003

m,n=X2.shape
print(m,n)

2 2


In [0]:
for i in range(10000):
  h=sigmoid(X2.dot(theta2))
  d=(Y2.dot(np.log(h).T)) + (1-Y2).dot(np.log(1-h).T)
  cost=-(1/m)*(d)
  theta2=theta2- alpha*(X2.T.dot(h-Y2))
  if i%100==0:
    print(theta2)

[[0.83213567]
 [0.16241514]]
[[ 0.71803566]
 [-0.04642535]]
[[ 0.6305504 ]
 [-0.23528995]]
[[ 0.56651996]
 [-0.40582941]]
[[ 0.52229434]
 [-0.56029441]]
[[ 0.49431398]
 [-0.70102831]]
[[ 0.47941323]
 [-0.83018243]]
[[ 0.47491982]
 [-0.9496052 ]]
[[ 0.47864316]
 [-1.06082982]]
[[ 0.4888158 ]
 [-1.16510593]]
[[ 0.50402311]
 [-1.26344491]]
[[ 0.52313691]
 [-1.35666451]]
[[ 0.54525843]
 [-1.44542786]]
[[ 0.56967153]
 [-1.53027546]]
[[ 0.59580518]
 [-1.61165067]]
[[ 0.62320371]
 [-1.68991991]]
[[ 0.65150334]
 [-1.7653883 ]]
[[ 0.68041359]
 [-1.83831197]]
[[ 0.70970263]
 [-1.90890767]]
[[ 0.73918567]
 [-1.97736034]]
[[ 0.76871573]
 [-2.04382901]]
[[ 0.79817626]
 [-2.10845152]]
[[ 0.82747528]
 [-2.17134827]]
[[ 0.85654064]
 [-2.23262519]]
[[ 0.88531625]
 [-2.29237615]]
[[ 0.91375899]
 [-2.35068492]]
[[ 0.94183623]
 [-2.4076267 ]]
[[ 0.96952387]
 [-2.46326942]]
[[ 0.99680469]
 [-2.51767482]]
[[ 1.023667  ]
 [-2.57089925]]
[[ 1.05010362]
 [-2.62299447]]
[[ 1.07611095]
 [-2.67400814]]
[[ 1.10168

In [0]:
print(theta1)
ans=predict(theta2,np.array([[1,0]]))
ans=ans[0][0]
print(round(ans))

[[0.96476444]
 [0.01545401]
 [0.11811727]]
1.0
